theme[main_bg]="#111014"
theme[main_fg]="#E7E2EA"

theme[title]="#D6B5F5"
theme[hi_fg]="#BD63FF"

theme[selected_bg]="#33233F"
theme[selected_fg]="#FFFFFF"

theme[inactive_fg]="#69636F"
theme[graph_text]="#918799"
theme[meter_bg]="#2A252F"

theme[proc_misc]="#A970FF"

theme[cpu_box]="#BD63FF"
theme[mem_box]="#8B6AA6"
theme[net_box]="#705382"
theme[proc_box]="#BD63FF"

theme[div_line]="#4B3A57"

theme[temp_start]="#70CFE3"
theme[temp_mid]="#E6C875"
theme[temp_end]="#FF6B81"

theme[cpu_start]="#5D4770"
theme[cpu_mid]="#A970FF"
theme[cpu_end]="#D89AFF"

theme[free_start]="#4B3A57"
theme[free_mid]="#8B6AA6"
theme[free_end]="#D6B5F5"

theme[cached_start]="#456F59"
theme[cached_mid]="#75D6A5"
theme[cached_end]="#92E3B8"

theme[available_start]="#43577D"
theme[available_mid]="#7297FF"
theme[available_end]="#8FAAFF"

theme[used_start]="#6E4783"
theme[used_mid]="#BC61FF"
theme[used_end]="#E879F9"

theme[download_start]="#43577D"
theme[download_mid]="#7297FF"
theme[download_end]="#70CFE3"

theme[upload_start]="#6E4783"
theme[upload_mid]="#BC61FF"
theme[upload_end]="#D89AFF"

theme[process_start]="#75D6A5"
theme[process_mid]="#A970FF"
theme[process_end]="#FF6B81"

theme[proc_pause_bg]="#33233F"
theme[proc_follow_bg]="#251A2D"
theme[proc_banner_bg]="#33233F"
theme[proc_banner_fg]="#D6B5F5"

theme[followed_bg]="#251A2D"
theme[followed_fg]="#FFFFFF"